dashboard:
  listen: 12335
  admin-pass: admin@pass
gokeeper:
  discover: gokeeper:7001
  admin-addr: gokeeper:17000
  domain: pepperbus-test
ldap:
  enable: true
  address: ldap:389
  base-dn: ""
mysql:
  host: mysql
  port: 3306
  database: dashboard
  username: root
  password: huajiao.tv-123
redis:
  host: redis
  port: 6379
  password:
  db: 0
etcd:
  endpoints:
    - http://gokeeper_etcd:2379
  username:
  password: