version: '3'

services:

  redis:
    image: redis:4-alpine
    ports:
      - 6379

  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - LANG=C.UTF-8
      - MYSQL_DATABASE=dashboard
      - MYSQL_ROOT_PASSWORD=huajiao.tv-123
    command:
      ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  peppercron:
    image: huajiao/peppercron
    entrypoint:
      [
        "/bin/sh", "-c",
        "/data/peppercron/peppercron -e http://gokeeper_etcd:2379 -n peppercron",
      ]
    environment:
      - DOCKER_ENV=true
    ports:
      - 12306
      - 12307
    depends_on:
      - redis
      - mysql
      - gokeeper_etcd

  php-fpm:
    image: huajiao/php-fpm
    volumes:
      - "./example/php:/data"

  pepperbus:
    image: huajiao/pepperbus
    command:
      [
        "/bin/sh", "-c",
        "/data/pepperbus/pepperbus -n pepperbus:19840 -d pepperbus-test -k gokeeper:7000 -kd gokeeper:7001",
      ]
    ports:
      - 12017
      - 19840
    depends_on:
      - gokeeper

  dashboard:
    image: huajiao/dashboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8360:80
    depends_on:
      - redis
      - mysql
      - gokeeper
      - peppercron

  gokeeper_etcd:
    image: quay.io/coreos/etcd:v3.3.18
    ports:
      - 2379
      - 2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379

  gokeeper:
    image: huajiao/gokeeper
    ports:
      - 7000
      - 7001
      - 17000
      - 17001
    environment:
      - DEFAULT_CLUSTER=pepperbus-test
    volumes:
      - "./deploy/gokeeper/pepperbus-test:/tmp/gokeeper/init/pepperbus-test"
    depends_on:
      - gokeeper_etcd